#!/bin/bash

# Cupcake Kafka API Testing Examples for localhost:9093
# =====================================================

echo "🧁 Cupcake Kafka API - curl Examples for localhost:9093"
echo "========================================================"
echo ""

API_BASE="http://localhost:8080"

echo "1. Basic Health Check:"
echo "curl -X GET ${API_BASE}/health"
echo ""

echo "2. Simple Kafka Message:"
echo "curl -X POST ${API_BASE}/api/kafka/publish \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"broker\": \"localhost:9093\","
echo "    \"topic\": \"test-topic\","
echo "    \"key\": \"simple-key\","
echo "    \"value\": \"{\\\"message\\\": \\\"Hello Kafka!\\\"}\""
echo "  }'"
echo ""

echo "3. Complex JSON Message:"
echo "curl -X POST ${API_BASE}/api/kafka/publish \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"broker\": \"localhost:9093\","
echo "    \"topic\": \"user-events\","
echo "    \"key\": \"user-123\","
echo "    \"value\": \"{\\\"eventType\\\": \\\"login\\\", \\\"userId\\\": 123, \\\"timestamp\\\": \\\"$(date -Iseconds)\\\", \\\"metadata\\\": {\\\"ip\\\": \\\"192.168.1.1\\\", \\\"userAgent\\\": \\\"curl\\\"}}\""
echo "  }'"
echo ""

echo "4. Using a JSON file:"
echo "# Create test-message-9093.json:"
echo "cat > test-message-9093.json << EOF"
echo "{"
echo "  \"broker\": \"localhost:9093\","
echo "  \"topic\": \"orders\","
echo "  \"key\": \"order-456\","
echo "  \"value\": \"{\\\"orderId\\\": 456, \\\"customerId\\\": 789, \\\"amount\\\": 99.99, \\\"status\\\": \\\"pending\\\"}\""
echo "}"
echo "EOF"
echo ""
echo "# Then send it:"
echo "curl -X POST ${API_BASE}/api/kafka/publish \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d @test-message-9093.json"
echo ""

echo "5. Postman Collection JSON:"
echo "# Import this into Postman:"
echo "{"
echo "  \"info\": {"
echo "    \"name\": \"Cupcake Kafka API\","
echo "    \"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\""
echo "  },"
echo "  \"item\": ["
echo "    {"
echo "      \"name\": \"Health Check\","
echo "      \"request\": {"
echo "        \"method\": \"GET\","
echo "        \"header\": [],"
echo "        \"url\": {"
echo "          \"raw\": \"${API_BASE}/health\","
echo "          \"host\": [\"localhost\"],"
echo "          \"port\": \"8080\","
echo "          \"path\": [\"health\"]"
echo "        }"
echo "      }"
echo "    },"
echo "    {"
echo "      \"name\": \"Publish Kafka Message\","
echo "      \"request\": {"
echo "        \"method\": \"POST\","
echo "        \"header\": ["
echo "          {"
echo "            \"key\": \"Content-Type\","
echo "            \"value\": \"application/json\""
echo "          }"
echo "        ],"
echo "        \"body\": {"
echo "          \"mode\": \"raw\","
echo "          \"raw\": \"{\\n  \\\"broker\\\": \\\"localhost:9093\\\",\\n  \\\"topic\\\": \\\"test-topic\\\",\\n  \\\"key\\\": \\\"test-key\\\",\\n  \\\"value\\\": \\\"{\\\\\\\"message\\\\\\\": \\\\\\\"Hello from Postman!\\\\\\\"}\\\"}\\n}\""
echo "        },"
echo "        \"url\": {"
echo "          \"raw\": \"${API_BASE}/api/kafka/publish\","
echo "          \"host\": [\"localhost\"],"
echo "          \"port\": \"8080\","
echo "          \"path\": [\"api\", \"kafka\", \"publish\"]"
echo "        }"
echo "      }"
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "📚 Documentation URLs:"
echo "   Swagger UI: ${API_BASE}/swagger/index.html"
echo "   Health: ${API_BASE}/health"
echo ""
echo "💡 Make sure your Kafka is running on localhost:9093!"
